import { Button } from "../components/ui/button";

import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Passport from '../components/Passport';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Benchmarker</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <Passport />

        <div className="mt-8">
          <Button>Click me</Button>
        </div>
        
      </main>

    </div>
  );
};

export default Home;
