
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';

import { Button } from "../../components/ui/button"
import { Input } from "../../components/ui/input"
import { Label } from "../../components/ui/label"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../../components/ui/card"


const Portfolio: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

      <Card className="w-[550px]">
          <CardHeader>
            <CardTitle>Portfolio</CardTitle>
            <CardDescription>Monitor all active positions.</CardDescription>
          </CardHeader>
          <CardContent>
            <form>
              <Card className='p-4 mb-6'>
                <CardContent>
                  One
                </CardContent>
              </Card>
              <Card className='p-4 mb-6'>
                <CardContent>
                  Two
                </CardContent>
              </Card>
            </form>
          </CardContent>
        </Card>


      </main>

    </div>
  );
};

export default Portfolio;
