
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';

import { CalendarDays } from "lucide-react"

import { Button } from "../../components/ui/button"
import { Input } from "../../components/ui/input"
import { Label } from "../../components/ui/label"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../../components/ui/card"
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "../../components/ui/tabs"


const portfolioItem = 
  {
    title: "ETH $10/Day",
    text1: "You need to deposit within 3 days.",
    text2: "",
    dateText: "9 Sep 2023",
    detail: {
      dailyInvestment: "$10",
      periodsCompleted: "1 out of 30",
      invested: "$10",
      accruedEth: "0.006 (-$1620 avg price)",
      awaitingDeposit: "$260",
      available: "$30",
      deposit: 100,
      message: "You need to deposit within 3 days.",
    },
    transactions:[
      {
        title: "$10 USDC -> 0.03 ETH",
        dateText: "9 Sep 2023 1:00 pm",
      },
      {
        title: "Inssuficient funds",
        dateText: "8 Sep 2023 1:00 pm",
      },
      {
        title: "Transaction Failed",
        dateText: "& Sep 2023 1:00 pm",
      },
      {
        title: "$10 USDC -> 0.03 ETH",
        dateText: "10 Sep 2023 1:00 pm",
      },
    ]
  };

const Portfolio: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

        <Tabs defaultValue="summ" className="w-[400px]">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="summ">Summary</TabsTrigger>
            <TabsTrigger value="trans">Transactions</TabsTrigger>
          </TabsList>
          <TabsContent value="summ">
            <Card>
              <CardHeader>
                <CardTitle>ETH</CardTitle>
                <CardDescription>
                  Manage your individual position.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="space-y-1">
                  <Label htmlFor="name">Daily Investment:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.dailyInvestment} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Periods Completed:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.periodsCompleted} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Invested:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.invested} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Accrued ETH:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.accruedEth} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Awaiting Deposit:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.awaitingDeposit} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Available:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.available} className="bg-secondary/100" readOnly />
                </div>
                <div className="space-y-1">
                  <Label htmlFor="name">Deposit:</Label>
                  <Input id="name" defaultValue={portfolioItem.detail.deposit} />
                </div>
                <div className="space-y-1">
                  <p className="text-red-500">{portfolioItem.detail.message}</p>  
                </div>
              </CardContent>
              <CardFooter className='justify-between'>
                <Button variant={"outline"}>Cancel</Button>
                <Button>Closed</Button>
              </CardFooter>
            </Card>
          </TabsContent>
          <TabsContent value="trans">
            <Card>
              <CardHeader>
                <CardTitle>ETH</CardTitle>
                <CardDescription>
                  Check your transaction history.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
              { portfolioItem.transactions.map((portfolioTransaction, i) => (
                <Card key={"portfolio-" + i} className='p-4 mb-6'>
                  <CardContent>
                    <h1 className="mb-2"><b>{portfolioTransaction.title}</b></h1>
                    <span className='inline-flex'>
                      <CalendarDays className="h-6 w-6" /> 
                      <p className="ml-2">{portfolioTransaction.dateText}</p></span>
                  </CardContent>
                </Card>
              ))}
              </CardContent>
              <CardFooter>
                <Button>Save password</Button>
              </CardFooter>
            </Card>
          </TabsContent>
        </Tabs>

      </main>

    </div>
  );
};

export default Portfolio;
